#!/bin/sh

## hyphop ##

#= build windows boot disk
# https://gist.github.com/shanky061/5b3e0e0f5debb2c458e6

I=.win-re-arm
IMG=win-re-arm.img

BS=512
OF=2048 # blocks by 512 bytes

CMD(){
    echo "# $@"
    "$@" || exit 1
}

P=$IMG@@$((OF*BS))
CMD truncate -s 700M $IMG
CMD mformat -i $P -v WINRE -N FEEDEEED ::
CMD mcopy -smp -i $P $I/* ::

CMD mdir -i $P ::

(
echo label:dos
echo
echo start=$OF, type=e
) | sfdisk -q $IMG

sfdisk --dump $IMG

rsync -avzz --inplace $IMG root@dev-helper.local:/tmp/mounts/dev-helper/images/